---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kubetest
  name: kubetest-account
  namespace: kubetest

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: kubetest
  name: kubetest-role
  namespace: kubetest
rules:
  - apiGroups:
      - ''
    resources:
      - endpoints
      - nodes
      - pods
      - secrets
      - configmaps
    verbs:
      - list
      - watch
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: kubetest
  name: kubetest-rb
  namespace: kubetest
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubetest-role
subjects:
  - kind: ServiceAccount
    name: kubetest-account
    namespace: kubetest
